from turtle import *
from j_clock import Clock

class Kattintgato:

    scr = Screen()
    t = Turtle()
    t2 = Turtle()
    c = Clock(scr)

    def asd(self, fill:bool):
        xA = self.t.xcor()
        yA = self.t.ycor()
        rotA = self.t.heading()
        self.t.penup()
        self.t.forward(-7)
        self.t.right(90)
        self.t.forward(5)
        self.t.left(90)
        self.t.forward(80)
        self.t.pendown()
        if fill:
            self.t.begin_fill()
        self.t.left(135)
        self.t.forward(20)
        self.t.left(45)
        self.t.forward(60)
        self.t.left(45)
        self.t.forward(20)
        self.t.left(90)
        self.t.forward(20)
        self.t.left(45)
        self.t.forward(60)
        self.t.left(45)
        self.t.forward(20)
        if fill:
            self.t.end_fill()
        self.t.penup()
        self.t.goto(xA, yA)
        self.t.setheading(rotA)
        self.t.pendown()

    def asdB(self, fill:bool):
        self.t.penup()
        self.t.forward(80)
        self.t.setheading(-90)
        self.t.forward(20)
        self.t.pendown()
        if fill:
            self.t.begin_fill()
        xB = self.t.xcor()
        yB = self.t.ycor()
        rotB = self.t.heading()
        self.t.penup()
        self.t.forward(80)
        self.t.pendown()
        self.t.left(135)
        self.t.forward(20)
        self.t.left(45)
        self.t.forward(60)
        self.t.left(45)
        self.t.forward(20)
        self.t.left(90)
        self.t.forward(20)
        self.t.left(45)
        self.t.forward(60)
        self.t.left(45)
        self.t.forward(20)
        self.t.penup()
        if fill:
            self.t.end_fill()
        self.t.goto(xB, yB)
        self.t.pendown()
        self.t.setheading(rotB)

    def asdC(self, fill:bool):
        self.t.penup()
        self.t.forward(80)
        self.t.setheading(-90)
        self.t.forward(20)
        self.t.pendown()
        if fill:
            self.t.begin_fill()
        xC = self.t.xcor()
        yC = self.t.ycor()
        rotC = self.t.heading()
        self.t.penup()
        self.t.forward(80)
        self.t.pendown()
        self.t.left(135)
        self.t.forward(20)
        self.t.left(45)
        self.t.forward(60)
        self.t.left(45)
        self.t.forward(20)
        self.t.left(90)
        self.t.forward(20)
        self.t.left(45)
        self.t.forward(60)
        self.t.left(45)
        self.t.forward(20)
        self.t.penup()
        if fill:
            self.t.end_fill()
        self.t.goto(xC, yC)
        self.t.pendown()
        self.t.setheading(rotC)

    def asdD(self, fill:bool):
        self.t.penup()
        self.t.forward(80)
        self.t.forward(5)
        self.t.setheading(180)
        self.t.forward(15)
        self.t.pendown()
        if fill:
            self.t.begin_fill()
        xD = self.t.xcor()
        yD = self.t.ycor()
        rotD = self.t.heading()
        self.t.penup()
        self.t.forward(80)
        self.t.pendown()
        self.t.left(135)
        self.t.forward(20)
        self.t.left(45)
        self.t.forward(60)
        self.t.left(45)
        self.t.forward(20)
        self.t.left(90)
        self.t.forward(20)
        self.t.left(45)
        self.t.forward(60)
        self.t.left(45)
        self.t.forward(20)
        self.t.penup()
        if fill:
            self.t.end_fill()
        self.t.goto(xD, yD)
        self.t.pendown()
        self.t.setheading(rotD)

    def asdE(self, fill:bool):
        self.t.penup()
        self.t.forward(80)
        self.t.forward(5)
        self.t.setheading(90)
        self.t.forward(15)
        self.t.pendown()
        if fill:
            self.t.begin_fill()
        xE = self.t.xcor()
        yE = self.t.ycor()
        rotE = self.t.heading()
        self.t.penup()
        self.t.forward(80)
        self.t.pendown()
        self.t.left(135)
        self.t.forward(20)
        self.t.left(45)
        self.t.forward(60)
        self.t.left(45)
        self.t.forward(20)
        self.t.left(90)
        self.t.forward(20)
        self.t.left(45)
        self.t.forward(60)
        self.t.left(45)
        self.t.forward(20)
        self.t.penup()
        if fill:
            self.t.end_fill()
        self.t.goto(xE, yE)
        self.t.pendown()
        self.t.setheading(rotE)

    def asdF(self, fill:bool):
        self.t.penup()
        self.t.forward(20)
        self.t.forward(80)
        self.t.setheading(90)
        self.t.forward(-3)
        self.t.pendown()
        if fill:
            self.t.begin_fill()
        xF = self.t.xcor()
        yF = self.t.ycor()
        rotF = self.t.heading()
        self.t.penup()
        self.t.forward(80)
        self.t.pendown()
        self.t.left(135)
        self.t.forward(20)
        self.t.left(45)
        self.t.forward(60)
        self.t.left(45)
        self.t.forward(20)
        self.t.left(90)
        self.t.forward(20)
        self.t.left(45)
        self.t.forward(60)
        self.t.left(45)
        self.t.forward(20)
        self.t.penup()
        if fill:
            self.t.end_fill()
        self.t.goto(xF, yF)
        self.t.pendown()
        self.t.setheading(rotF)

    def asdG(self, fill:bool):
        self.t.penup()
        self.t.setheading(0)
        self.t.forward(-5)
        self.t.setheading(-90)
        self.t.forward(15)
        self.t.setheading(0)
        self.t.forward(20)
        self.t.pendown()
        if fill:
            self.t.begin_fill()
        xF = self.t.xcor()
        yF = self.t.ycor()
        rotF = self.t.heading()
        self.t.penup()
        self.t.forward(80)
        self.t.pendown()
        self.t.left(135)
        self.t.forward(20)
        self.t.left(45)
        self.t.forward(60)
        self.t.left(45)
        self.t.forward(20)
        self.t.left(90)
        self.t.forward(20)
        self.t.left(45)
        self.t.forward(60)
        self.t.left(45)
        self.t.forward(20)
        self.t.penup()
        if fill:
            self.t.end_fill()
        self.t.goto(xF, yF)
        self.t.pendown()
        self.t.setheading(rotF)

    def asd2(self):
        self.t2.fillcolor("green")
        self.t2.begin_fill()
        self.t2.penup()
        self.t2.forward(80)
        self.t2.pendown()
        self.t2.left(135)
        self.t2.forward(20)
        self.t2.left(45)
        self.t2.forward(60)
        self.t2.left(45)
        self.t2.forward(20)
        self.t2.left(90)
        self.t2.forward(20)
        self.t2.left(45)
        self.t2.forward(60)
        self.t2.left(45)
        self.t2.forward(20)
        self.t2.end_fill()

    def nulla(self):
        self.asd(True)
        self.asdB(True)
        self.asdC(True)
        self.asdD(True)
        self.asdE(True)
        self.asdF(True)
        self.asdG(False)

    def egy(self):
        self.asd(False)
        self.asdB(True)
        self.asdC(True)
        self.asdD(False)
        self.asdE(False)
        self.asdF(False)
        self.asdG(False)

    def ketto(self):
        self.asd(True)
        self.asdB(True)
        self.asdC(False)
        self.asdD(True)
        self.asdE(True)
        self.asdF(False)
        self.asdG(True)

    def harom(self):
        self.asd(True)
        self.asdB(True)
        self.asdC(True)
        self.asdD(True)
        self.asdE(False)
        self.asdF(False)
        self.asdG(True)

    def negy(self):
        self.asd(False)
        self.asdB(True)
        self.asdC(True)
        self.asdD(False)
        self.asdE(False)
        self.asdF(True)
        self.asdG(True)

    def ot(self):
        self.asd(True)
        self.asdB(False)
        self.asdC(True)
        self.asdD(True)
        self.asdE(False)
        self.asdF(True)
        self.asdG(True)

    def hat(self):
        self.asd(True)
        self.asdB(False)
        self.asdC(True)
        self.asdD(True)
        self.asdE(True)
        self.asdF(True)
        self.asdG(True)

    def het(self):
        self.asd(True)
        self.asdB(True)
        self.asdC(True)
        self.asdD(False)
        self.asdE(False)
        self.asdF(False)
        self.asdG(False)

    def nyolc(self):
        self.asd(True)
        self.asdB(True)
        self.asdC(True)
        self.asdD(True)
        self.asdE(True)
        self.asdF(True)
        self.asdG(True)

    def kilenc(self):
        self.asd(True)
        self.asdB(True)
        self.asdC(True)
        self.asdD(True)
        self.asdE(False)
        self.asdF(True)
        self.asdG(True)

    def secondright(self):
        if self.c.rightNumber(self.c.sec()) == 0:
            self.t2.clear()
            self.t2.penup()
            self.t2.goto(250, -150)
            self.t2.pendown()
            self.nulla()
        if self.c.rightNumber(self.c.sec()) == 1:
            self.t2.clear()
            self.t2.penup()
            self.t2.goto(150, -50)
            self.t2.pendown()
            self.egy()
        if self.c.rightNumber(self.c.sec()) == 2:
            self.t2.clear()
            self.t2.penup()
            self.t2.goto(150, -50)
            self.t2.pendown()
            self.ketto()
        if self.c.rightNumber(self.c.sec()) == 3:
            self.t2.clear()
            self.t2.penup()
            self.t2.goto(150, -50)
            self.t2.pendown()
            self.harom()
        if self.c.rightNumber(self.c.sec()) == 4:
            self.t2.clear()
            self.t2.penup()
            self.t2.goto(150, -50)
            self.t2.pendown()
            self.negy()
        if self.c.rightNumber(self.c.sec()) == 5:
            self.t2.clear()
            self.t2.penup()
            self.t2.goto(150, -50)
            self.t2.pendown()
            self.ot()
        if self.c.rightNumber(self.c.sec()) == 6:
            self.t2.clear()
            self.t2.penup()
            self.t2.goto(150, -50)
            self.t2.pendown()
            self.hat()
        if self.c.rightNumber(self.c.sec()) == 7:
            self.t2.clear()
            self.t2.penup()
            self.t2.goto(150, -50)
            self.t2.pendown()
            self.het()
        if self.c.rightNumber(self.c.sec()) == 8:
            self.t2.clear()
            self.t2.penup()
            self.t2.goto(150, -50)
            self.t2.pendown()
            self.nyolc()
        if self.c.rightNumber(self.c.sec()) == 9:
            self.t2.clear()
            self.t2.penup()
            self.t2.goto(150, -50)
            self.t2.pendown()
            self.kilenc()

    def secondleft(self):
        if self.c.leftNumber(self.c.sec()) == 0:
            self.t.clear()
            self.t.penup()
            self.t.goto(50, 0)
            self.t.pendown()
            self.nulla()
        if self.c.leftNumber(self.c.sec()) == 1:
            self.t.clear()
            self.t.penup()
            self.t.goto(0, 0)
            self.t.pendown()
            self.egy()
        if self.c.leftNumber(self.c.sec()) == 2:
            self.t.clear()
            self.t.penup()
            self.t.goto(0, 0)
            self.t.pendown()
            self.ketto()
        if self.c.leftNumber(self.c.sec()) == 3:
            self.t.clear()
            self.t.penup()
            self.t.goto(0, 0)
            self.t.pendown()
            self.harom()
        if self.c.leftNumber(self.c.sec()) == 4:
            self.t.clear()
            self.t.penup()
            self.t.goto(0, 0)
            self.t.pendown()
            self.negy()
        if self.c.leftNumber(self.c.sec()) == 5:
            self.t.clear()
            self.t.penup()
            self.t.goto(0, 0)
            self.t.pendown()
            self.ot()
        if self.c.leftNumber(self.c.sec()) == 6:
            self.t.clear()
            self.t.penup()
            self.t.goto(0, 0)
            self.t.pendown()
            self.hat()
        if self.c.leftNumber(self.c.sec()) == 7:
            self.t.clear()
            self.t.penup()
            self.t.goto(0, 0)
            self.t.pendown()
            self.het()
        if self.c.leftNumber(self.c.sec()) == 8:
            self.t.clear()
            self.t.penup()
            self.t.goto(0, 0)
            self.t.pendown()
            self.nyolc()
        if self.c.leftNumber(self.c.sec()) == 9:
            self.t.clear()
            self.t.penup()
            self.t.goto(0, 0)
            self.t.pendown()
            self.kilenc()

    def second(self):
        self.secondleft()
        self.secondright()

    def __init__(self):
        self.t.fillcolor("green")
        self.t._delay(0)
        self.t.speed(0)
        #self.kilenc()
        self.c.setOnSecondChangeListener(self.second)
        #self.asd()
        #self.asdB()
        #self.asdC()
        #self.asdD()
        #self.asdE()
        #self.asdF()
        #self.asdG()
        self.scr.mainloop()

Kattintgato()