from turtle import *
from j_clock import Clock

class Kattintgato:

    scr = Screen()
    t = Turtle()
    t2 = Turtle()
    c = Clock(scr)

    def asd(self):
        self.t.fillcolor("green")
        self.t.begin_fill()
        self.t.penup()
        self.t.forward(80)
        self.t.pendown()
        self.t.left(135)
        self.t.forward(20)
        self.t.left(45)
        self.t.forward(60)
        self.t.left(45)
        self.t.forward(20)
        self.t.left(90)
        self.t.forward(20)
        self.t.left(45)
        self.t.forward(60)
        self.t.left(45)
        self.t.forward(20)
        self.t.end_fill()

    #def asd2(self):
        #for i in range(3):
            #self.t.left(135)
            #self.t.forward(100)
            #self.t.left(90)

    #def asd3(self):
        #self.t.right(135)
        #self.asd()

    def nulla(self):
        x0 = self.t.xcor()
        y0 = self.t.ycor()
        heading0 = self.t.heading()
        self.t.left(90)
        self.asd()
        self.t.penup()
        self.t.right(45)
        self.t.forward(15)
        self.asd()
        self.t.penup()
        self.t.right(45)
        self.t.forward(10)
        self.t.left(90)
        self.t.forward(10)
        self.asd()
        self.t.penup()
        self.t.right(45)
        self.t.forward(2)
        self.t.left(90)
        self.t.forward(18)
        self.asd()
        self.t.penup()
        self.t.right(45)
        self.t.forward(15)
        self.asd()
        self.t.penup()
        self.t.right(45)
        self.t.forward(10)
        self.t.left(90)
        self.t.forward(10)
        self.asd()
        self.t.penup()
        self.t.goto(x0,y0)
        self.t.setheading(heading0)
        self.t.pendown()



    def egy(self):
        x = self.t.xcor()
        y = self.t.ycor()
        heading = self.t.heading()
        self.t.left(90)
        self.asd()
        self.t.right(45)
        self.t.penup()
        self.t.forward(15)
        self.t.pendown()
        self.asd()
        self.t.penup()
        self.t.goto(x,y)
        self.t.pendown()
        self.t.setheading(heading)

    def ketto(self):
        x2 = self.t.xcor()
        y2 = self.t.ycor()
        heading2 = self.t.heading()
        self.asd()
        for i in range(2):
            self.t.right(135)
            self.t.penup()
            self.t.forward(15)
            self.t.pendown()
            self.asd()
        for i in range(2):
            self.t.left(45)
            self.t.penup()
            self.t.forward(15)
            self.asd()
        self.t.penup()
        self.t.goto(x2,y2)
        self.t.pendown()
        self.t.setheading(heading2)

    def harom(self):
        x3 = self.t.xcor()
        y3 = self.t.ycor()
        heading3 = self.t.heading()
        self.asd()
        self.t.right(135)
        self.t.penup()
        self.t.forward(15)
        self.t.pendown()
        self.asd()
        self.t.right(45)
        self.t.penup()
        self.t.forward(15)
        self.asd()
        self.t.left(225)
        self.t.penup()
        self.t.forward(15)
        self.asd()
        self.t.right(130)
        self.t.penup()
        self.t.forward(90)
        self.t.right(95)
        self.t.penup()
        self.t.forward(16)
        self.asd()
        self.t.penup()
        self.t.goto(x3, y3)
        self.t.setheading(heading3)

    def negy(self):
        x4 = self.t.xcor()
        y4 = self.t.ycor()
        heading4 = self.t.heading()
        self.t.left(90)
        self.asd()
        self.t.right(45)
        self.t.penup()
        self.t.forward(10)
        self.t.left(90)
        self.t.forward(10)
        self.t.pendown()
        self.asd()
        self.t.right(135)
        self.t.penup()
        self.t.forward(10)
        self.t.forward(10)
        self.t.pendown()
        self.asd()
        self.t.right(135)
        self.t.penup()
        self.t.forward(90)
        self.t.right(90)
        self.t.forward(10)
        self.asd()
        self.t.penup()
        self.t.goto(x4,y4)
        self.t.pendown()
        self.t.setheading(heading4)

    def ot(self):
        x5 = self.t.xcor()
        y5 = self.t.ycor()
        heading5 = self.t.heading()
        self.t.left(180)
        self.asd()
        self.t.penup()
        self.t.left(45)
        self.t.forward(15)
        self.asd()
        self.t.penup()
        self.t.left(45)
        self.t.forward(15)
        self.asd()
        self.t.penup()
        self.t.right(135)
        self.t.forward(15)
        self.asd()
        self.t.penup()
        self.t.right(135)
        self.t.forward(15)
        self.asd()
        self.t.penup()
        self.t.goto(x5,y5)
        self.t.pendown()
        self.t.setheading(heading5)

    def hat(self):
        x6 = self.t.xcor()
        y6 = self.t.ycor()
        heading6 = self.t.heading()
        self.asd()
        self.t.penup()
        self.t.goto(x6, y6)
        self.t.pendown()
        self.t.setheading(heading6)
        self.t.right(90)
        self.t.penup()
        self.t.forward(20)
        self.asd()
        self.t.right(45)
        self.t.penup()
        self.t.forward(15)
        self.t.pendown()
        self.asd()
        self.t.left(45)
        self.t.penup()
        self.t.forward(15)
        self.t.pendown()
        self.asd()
        self.t.left(45)
        self.t.penup()
        self.t.forward(15)
        self.t.pendown()
        self.asd()
        self.t.left(45)
        self.t.penup()
        self.t.forward(12)
        self.t.pendown()
        self.asd()
        self.t.goto(x6, y6)
        self.t.pendown()
        self.t.setheading(heading6)

    def het(self):
        x7 = self.t.xcor()
        y7 = self.t.ycor()
        heading7 = self.t.heading()
        self.asd()
        self.t.right(135)
        self.t.penup()
        self.t.forward(15)
        self.t.pendown()
        self.asd()
        self.t.right(45)
        self.t.penup()
        self.t.forward(15)
        self.asd()
        self.t.penup()
        self.t.goto(x7,y7)
        self.t.pendown()
        self.t.setheading(heading7)


    def secondleft(self):
        if self.c.leftNumber(self.c.sec()) == 0:
            self.nulla()
            self.t.clear()
        if self.c.leftNumber(self.c.sec()) == 1:
            self.egy()
            self.t.clear()
        if self.c.leftNumber(self.c.sec()) == 2:
            self.ketto()
            self.t.clear()
        if self.c.leftNumber(self.c.sec()) == 3:
            self.harom()
            self.t.clear()
        if self.c.leftNumber(self.c.sec()) == 4:
            self.negy()
            self.t.clear()
        if self.c.leftNumber(self.c.sec()) == 5:
            self.ot()
            self.t.clear()
        if self.c.leftNumber(self.c.sec()) == 7:
            self.het()
            self.t.clear()

    def __init__(self):
        self.t.fillcolor("yellow")
        self.t2.fillcolor("yellow")
        self.hat()

        self.t._delay(0)
        self.t.speed(0)

        self.scr.mainloop()


Kattintgato()